# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

highlighter:      pygments


# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sahir B
tagline:          'Sahir Bhatnagar'
description:	  'Find me on twitter <a href="https://twitter.com/syfi_24" target="_blank">@syfi_24</a>, <a href="https://github.com/sahirbhatnagar">Github</a>, <a href="mailto:sahir.bhatnagar@gmail.com">email</a>'
#description:      'PhD student in <a href="http://www.mcgill.ca/epi-biostat-occh/" target="_blank">Biostatistics</a> at <a href="http://mcgill.ca" target="_blank">McGill Univeristy</a> under the #supervision of <a href="http://www.mcgill.ca/statisticalgenetics/" target="_blank">Celia Greenwood</a> and <a href="http://en.wikipedia.org/wiki/Mathieu_Blanchette_%28computational_biologist%29" #target="_blank">Mathieu Blanchette</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Sahir Bhatnagar'
  url:            https://twitter.com/syfi_24

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sahirbhatnagar/
